-- Customers
INSERT INTO customers (name, email, city, country) VALUES ('Allison Hill', 'donaldgarcia@example.net', 'New Roberttown', 'Bermuda');
INSERT INTO customers (name, email, city, country) VALUES ('Jonathan Johnson', 'jennifermiles@example.com', 'South Bridget', 'Sudan');
INSERT INTO customers (name, email, city, country) VALUES ('Olivia Moore', 'jpeterson@example.org', 'Curtisfurt', 'Bhutan');
INSERT INTO customers (name, email, city, country) VALUES ('Gregory Baker', 'blairamanda@example.com', 'New Kellystad', 'Morocco');
INSERT INTO customers (name, email, city, country) VALUES ('Benjamin Stanley', 'tracie31@example.com', 'Shawnstad', 'Central African Republic');
INSERT INTO customers (name, email, city, country) VALUES ('Daniel Adams', 'lynchgeorge@example.net', 'East Steven', 'Faroe Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Margaret Hawkins DDS', 'perezantonio@example.com', 'Adamsborough', 'United States Minor Outlying Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Sherri Edwards', 'pfoster@example.com', 'West Donald', 'Samoa');
INSERT INTO customers (name, email, city, country) VALUES ('Deborah Richards', 'icox@example.net', 'Daviston', 'Tokelau');
INSERT INTO customers (name, email, city, country) VALUES ('Mark Conner', 'ycarlson@example.com', 'Riceside', 'Tokelau');
INSERT INTO customers (name, email, city, country) VALUES ('Melanie Wilson', 'kayla51@example.com', 'Mooretown', 'Zimbabwe');
INSERT INTO customers (name, email, city, country) VALUES ('Michelle Stanton', 'williamrodriguez@example.net', 'Meaganhaven', 'New Caledonia');
INSERT INTO customers (name, email, city, country) VALUES ('James Martin', 'georgetracy@example.org', 'Natashaport', 'Dominican Republic');
INSERT INTO customers (name, email, city, country) VALUES ('Shawn Arroyo', 'dennislisa@example.net', 'East Donna', 'Yemen');
INSERT INTO customers (name, email, city, country) VALUES ('Deborah Brennan', 'ibrandt@example.net', 'Lake Larry', 'Paraguay');
INSERT INTO customers (name, email, city, country) VALUES ('Jessica Holmes', 'wrightcaleb@example.org', 'New Jeffrey', 'Barbados');
INSERT INTO customers (name, email, city, country) VALUES ('Amy Jones', 'heathchad@example.org', 'Elizabethborough', 'Mauritius');
INSERT INTO customers (name, email, city, country) VALUES ('Timothy Duncan', 'esanchez@example.com', 'North Collin', 'Jersey');
INSERT INTO customers (name, email, city, country) VALUES ('Jason Shields', 'nuneztracey@example.org', 'South Jessicaville', 'Egypt');
INSERT INTO customers (name, email, city, country) VALUES ('Joshua Taylor', 'joshuawright@example.org', 'Mortonside', 'Bolivia');
INSERT INTO customers (name, email, city, country) VALUES ('Zachary Huff', 'housemelinda@example.org', 'Tuckerborough', 'Tonga');
INSERT INTO customers (name, email, city, country) VALUES ('Anthony Gray', 'ybaker@example.com', 'Rodneyside', 'Panama');
INSERT INTO customers (name, email, city, country) VALUES ('Brittney Phillips', 'rileyamy@example.net', 'Brianshire', 'Lesotho');
INSERT INTO customers (name, email, city, country) VALUES ('Sarah Moore', 'yorkcasey@example.org', 'South David', 'Tuvalu');
INSERT INTO customers (name, email, city, country) VALUES ('Lauren Williams', 'barnesbrandy@example.net', 'Sarahborough', 'Paraguay');
INSERT INTO customers (name, email, city, country) VALUES ('Cynthia Foster', 'stephen10@example.com', 'North Amandahaven', 'Estonia');
INSERT INTO customers (name, email, city, country) VALUES ('Gregory Jones', 'mikemoore@example.net', 'Cherylhaven', 'Algeria');
INSERT INTO customers (name, email, city, country) VALUES ('Kristen Huynh', 'mcmillandennis@example.org', 'Lake Angelaview', 'Finland');
INSERT INTO customers (name, email, city, country) VALUES ('Michelle Harris', 'william40@example.org', 'Calderonton', 'Afghanistan');
INSERT INTO customers (name, email, city, country) VALUES ('Carlos Whitney', 'joycearnold@example.com', 'North Charlesberg', 'Mayotte');
INSERT INTO customers (name, email, city, country) VALUES ('Jacob Tran', 'tanderson@example.com', 'West Jasonbury', 'Papua New Guinea');
INSERT INTO customers (name, email, city, country) VALUES ('Richard Henson', 'vdickson@example.org', 'Port Francisco', 'South Georgia and the South Sandwich Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Sierra Johnson', 'kimberly63@example.com', 'Port Jacqueline', 'Hong Kong');
INSERT INTO customers (name, email, city, country) VALUES ('Shannon Walker', 'ybailey@example.org', 'North Donna', 'Iran');
INSERT INTO customers (name, email, city, country) VALUES ('Sean Rasmussen', 'michael86@example.net', 'Sheilaville', 'Turkey');
INSERT INTO customers (name, email, city, country) VALUES ('Cassandra Estes', 'benjamin96@example.com', 'Samuelhaven', 'Brazil');
INSERT INTO customers (name, email, city, country) VALUES ('Kenneth Scott', 'zsmith@example.net', 'West Ryan', 'Yemen');
INSERT INTO customers (name, email, city, country) VALUES ('Erin Edwards', 'cortezkevin@example.com', 'Nguyenport', 'Micronesia');
INSERT INTO customers (name, email, city, country) VALUES ('Jason Bentley', 'christinaturner@example.net', 'West Justinchester', 'Solomon Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Mary Marshall', 'glowe@example.com', 'Lake Christopher', 'Malaysia');
INSERT INTO customers (name, email, city, country) VALUES ('Lisa Davis', 'emilywalker@example.org', 'North Brandon', 'Lebanon');
INSERT INTO customers (name, email, city, country) VALUES ('Patricia Gibson', 'jennifercruz@example.com', 'East Diana', 'Albania');
INSERT INTO customers (name, email, city, country) VALUES ('Shannon Mcclure', 'zrobinson@example.net', 'Williamsbury', 'United States Virgin Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Joyce Solis', 'stephanie79@example.net', 'Rivasside', 'Kiribati');
INSERT INTO customers (name, email, city, country) VALUES ('Natasha Wells', 'karen48@example.com', 'West Scott', 'Rwanda');
INSERT INTO customers (name, email, city, country) VALUES ('Devon Flores', 'taylorjesse@example.net', 'Lake Jason', 'Israel');
INSERT INTO customers (name, email, city, country) VALUES ('Joshua Perry', 'marissaprice@example.net', 'Port Nicoleshire', 'Hong Kong');
INSERT INTO customers (name, email, city, country) VALUES ('Tommy Evans', 'acastaneda@example.net', 'South Jeffrey', 'Jordan');
INSERT INTO customers (name, email, city, country) VALUES ('Mr. Michael Yates', 'marycalhoun@example.net', 'South Brittanytown', 'Belize');
INSERT INTO customers (name, email, city, country) VALUES ('Brandy Murray', 'greenmark@example.com', 'Matthewfurt', 'Fiji');
INSERT INTO customers (name, email, city, country) VALUES ('Sandra King', 'ruizkaitlyn@example.org', 'Jeffreyland', 'Slovakia (Slovak Republic)');
INSERT INTO customers (name, email, city, country) VALUES ('Amanda Johnson', 'jamessmith@example.org', 'East Thomas', 'Brazil');
INSERT INTO customers (name, email, city, country) VALUES ('Claudia Lyons', 'gary91@example.org', 'Danieltown', 'Vanuatu');
INSERT INTO customers (name, email, city, country) VALUES ('Michael Rubio', 'mdavid@example.org', 'North Heidi', 'Gabon');
INSERT INTO customers (name, email, city, country) VALUES ('Lindsay Martinez', 'reedross@example.com', 'New Deborahtown', 'Thailand');
INSERT INTO customers (name, email, city, country) VALUES ('John Hamilton', 'cynthia72@example.com', 'Lake Aimee', 'Pakistan');
INSERT INTO customers (name, email, city, country) VALUES ('Robert Medina', 'umarshall@example.net', 'Marcusbury', 'Switzerland');
INSERT INTO customers (name, email, city, country) VALUES ('Diana Hayes', 'qhudson@example.com', 'Anthonymouth', 'Cocos (Keeling) Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Mr. David Ramirez', 'angela83@example.org', 'Lake Richard', 'Moldova');
INSERT INTO customers (name, email, city, country) VALUES ('Melissa Brewer', 'bwest@example.org', 'Jeffreybury', 'Gambia');
INSERT INTO customers (name, email, city, country) VALUES ('Jackie Tran', 'ronald85@example.com', 'Nelsonview', 'Djibouti');
INSERT INTO customers (name, email, city, country) VALUES ('Corey Wilson', 'jamesrodgers@example.com', 'Tinaborough', 'French Polynesia');
INSERT INTO customers (name, email, city, country) VALUES ('Christopher Smith', 'joshuamccann@example.net', 'Heidiberg', 'Northern Mariana Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Katherine Salas', 'taylor75@example.org', 'West Shelleyfort', 'Brazil');
INSERT INTO customers (name, email, city, country) VALUES ('Jennifer Jones', 'hernandezlisa@example.com', 'East Davidchester', 'New Caledonia');
INSERT INTO customers (name, email, city, country) VALUES ('Lisa Rowe', 'chayes@example.com', 'Torreston', 'New Zealand');
INSERT INTO customers (name, email, city, country) VALUES ('Annette Farmer', 'josephmiller@example.org', 'New Charles', 'Afghanistan');
INSERT INTO customers (name, email, city, country) VALUES ('Michael Harrison', 'halljasmine@example.net', 'Jonesbury', 'Uzbekistan');
INSERT INTO customers (name, email, city, country) VALUES ('Rick Lawrence', 'ronaldstephens@example.net', 'West Margaret', 'Barbados');
INSERT INTO customers (name, email, city, country) VALUES ('Ricky Larson', 'scott74@example.net', 'Benderhaven', 'Mauritius');
INSERT INTO customers (name, email, city, country) VALUES ('Bobby Williams MD', 'cassandra01@example.org', 'Port Emilyview', 'Morocco');
INSERT INTO customers (name, email, city, country) VALUES ('Peter Ruiz', 'lmoon@example.net', 'Waltersfort', 'Bermuda');
INSERT INTO customers (name, email, city, country) VALUES ('Jason Morris', 'hodgemark@example.net', 'Robertsfurt', 'Suriname');
INSERT INTO customers (name, email, city, country) VALUES ('Amanda Miller', 'marcus68@example.org', 'Gutierrezborough', 'Maldives');
INSERT INTO customers (name, email, city, country) VALUES ('Peter Garrett', 'harrisandrea@example.com', 'Gilmorefort', 'British Virgin Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Mark Lloyd', 'lancesmith@example.com', 'East Victoriaville', 'Kyrgyz Republic');
INSERT INTO customers (name, email, city, country) VALUES ('Maria Moore', 'william46@example.com', 'Sanchezside', 'Cameroon');
INSERT INTO customers (name, email, city, country) VALUES ('Thomas Romero', 'michellehill@example.com', 'Sarahhaven', 'Ethiopia');
INSERT INTO customers (name, email, city, country) VALUES ('Diane Evans', 'cgrimes@example.net', 'Reedside', 'Serbia');
INSERT INTO customers (name, email, city, country) VALUES ('Jordan Morris', 'tinaallen@example.com', 'Port Kimberly', 'Aruba');
INSERT INTO customers (name, email, city, country) VALUES ('John Mcintyre', 'qhughes@example.net', 'South Tammie', 'Brunei Darussalam');
INSERT INTO customers (name, email, city, country) VALUES ('Leslie Kane', 'dgarcia@example.org', 'South Monica', 'Cape Verde');
INSERT INTO customers (name, email, city, country) VALUES ('Richard Baker', 'vsantos@example.net', 'Finleyfort', 'Tunisia');
INSERT INTO customers (name, email, city, country) VALUES ('Lisa Young', 'wendy16@example.org', 'South Garrettport', 'United Kingdom');
INSERT INTO customers (name, email, city, country) VALUES ('Frederick Brown', 'nicholas23@example.net', 'Knightburgh', 'Chile');
INSERT INTO customers (name, email, city, country) VALUES ('Leon Reyes', 'tyleraguilar@example.org', 'Littlemouth', 'Equatorial Guinea');
INSERT INTO customers (name, email, city, country) VALUES ('Stephanie Marshall', 'erica21@example.com', 'Vanessaport', 'Northern Mariana Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Melissa Bryant', 'james67@example.org', 'South Ashley', 'Morocco');
INSERT INTO customers (name, email, city, country) VALUES ('Michael Johnson', 'khill@example.net', 'New Julieport', 'Singapore');
INSERT INTO customers (name, email, city, country) VALUES ('Lisa Gomez', 'christinebyrd@example.net', 'Lake Colton', 'Niue');
INSERT INTO customers (name, email, city, country) VALUES ('Ellen Alexander', 'jessica14@example.com', 'Thompsonberg', 'Solomon Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Valerie Schmidt', 'maria47@example.com', 'Lindamouth', 'Belarus');
INSERT INTO customers (name, email, city, country) VALUES ('Vincent Dalton', 'zcoffey@example.net', 'Christopherfurt', 'American Samoa');
INSERT INTO customers (name, email, city, country) VALUES ('Caleb Richardson', 'brenda51@example.net', 'South Angel', 'Turks and Caicos Islands');
INSERT INTO customers (name, email, city, country) VALUES ('Erin Bishop', 'reidsteven@example.net', 'Debraville', 'Burundi');
INSERT INTO customers (name, email, city, country) VALUES ('Andrew Ferrell', 'davispaige@example.org', 'Chavezside', 'Italy');
INSERT INTO customers (name, email, city, country) VALUES ('Molly Mcclure', 'basschristina@example.com', 'Lake Mitchellmouth', 'Kenya');
INSERT INTO customers (name, email, city, country) VALUES ('Savannah Garcia', 'amy50@example.com', 'Jamesville', 'Yemen');
INSERT INTO customers (name, email, city, country) VALUES ('Jordan Bates', 'williamsmatthew@example.org', 'North Maria', 'Micronesia');
INSERT INTO customers (name, email, city, country) VALUES ('Daniel Kane', 'kim90@example.com', 'East Amber', 'South Georgia and the South Sandwich Islands');

-- Products
INSERT INTO products (name, category, price, stock) VALUES ('Contain Break', 'Kitchen', 417.26, 33);
INSERT INTO products (name, category, price, stock) VALUES ('Recent Trial', 'Toys', 495.91, 6);
INSERT INTO products (name, category, price, stock) VALUES ('Agree Catch', 'Books', 334.83, 52);
INSERT INTO products (name, category, price, stock) VALUES ('Administration Help', 'Clothing', 344.22, 98);
INSERT INTO products (name, category, price, stock) VALUES ('Strategy Story', 'Clothing', 58.25, 15);
INSERT INTO products (name, category, price, stock) VALUES ('Economy Per', 'Toys', 224.37, 14);
INSERT INTO products (name, category, price, stock) VALUES ('Game Admit', 'Kitchen', 406.85, 5);
INSERT INTO products (name, category, price, stock) VALUES ('Contain Evidence', 'Electronics', 125.95, 97);
INSERT INTO products (name, category, price, stock) VALUES ('Area Card', 'Books', 476.58, 71);
INSERT INTO products (name, category, price, stock) VALUES ('Site Know', 'Toys', 182.92, 36);
INSERT INTO products (name, category, price, stock) VALUES ('Never Build', 'Toys', 290.55, 8);
INSERT INTO products (name, category, price, stock) VALUES ('Skill Attack', 'Books', 35.24, 85);
INSERT INTO products (name, category, price, stock) VALUES ('Maybe List', 'Books', 169.64, 38);
INSERT INTO products (name, category, price, stock) VALUES ('Star High', 'Books', 263.67, 81);
INSERT INTO products (name, category, price, stock) VALUES ('Must Personal', 'Kitchen', 386.21, 77);
INSERT INTO products (name, category, price, stock) VALUES ('Boy Live', 'Books', 115.46, 72);
INSERT INTO products (name, category, price, stock) VALUES ('Most Do', 'Books', 389.11, 32);
INSERT INTO products (name, category, price, stock) VALUES ('Young Possible', 'Kitchen', 102.39, 71);
INSERT INTO products (name, category, price, stock) VALUES ('Animal Short', 'Books', 450.81, 92);
INSERT INTO products (name, category, price, stock) VALUES ('Step When', 'Kitchen', 169.44, 18);
INSERT INTO products (name, category, price, stock) VALUES ('Trial Reason', 'Electronics', 440.22, 45);
INSERT INTO products (name, category, price, stock) VALUES ('Near Fish', 'Books', 261.0, 59);
INSERT INTO products (name, category, price, stock) VALUES ('Low Question', 'Kitchen', 372.41, 23);
INSERT INTO products (name, category, price, stock) VALUES ('Allow Ask', 'Kitchen', 188.29, 71);
INSERT INTO products (name, category, price, stock) VALUES ('Measure Throw', 'Kitchen', 480.62, 92);
INSERT INTO products (name, category, price, stock) VALUES ('Interest Last', 'Electronics', 29.0, 57);
INSERT INTO products (name, category, price, stock) VALUES ('Rich Box', 'Kitchen', 436.35, 80);
INSERT INTO products (name, category, price, stock) VALUES ('Military Seem', 'Electronics', 263.24, 38);
INSERT INTO products (name, category, price, stock) VALUES ('Where Life', 'Electronics', 153.3, 34);
INSERT INTO products (name, category, price, stock) VALUES ('Back Way', 'Books', 61.01, 100);
INSERT INTO products (name, category, price, stock) VALUES ('Be Fund', 'Clothing', 191.16, 67);
INSERT INTO products (name, category, price, stock) VALUES ('Political Choose', 'Electronics', 171.51, 56);
INSERT INTO products (name, category, price, stock) VALUES ('Attorney Card', 'Kitchen', 178.08, 18);
INSERT INTO products (name, category, price, stock) VALUES ('Face Probably', 'Books', 41.6, 57);
INSERT INTO products (name, category, price, stock) VALUES ('Property Pay', 'Clothing', 139.1, 16);
INSERT INTO products (name, category, price, stock) VALUES ('Official Seem', 'Clothing', 450.67, 23);
INSERT INTO products (name, category, price, stock) VALUES ('Garden I', 'Clothing', 282.51, 97);
INSERT INTO products (name, category, price, stock) VALUES ('Picture Nice', 'Clothing', 303.66, 21);
INSERT INTO products (name, category, price, stock) VALUES ('Financial Long', 'Books', 174.99, 6);
INSERT INTO products (name, category, price, stock) VALUES ('Mouth Point', 'Toys', 263.19, 69);
INSERT INTO products (name, category, price, stock) VALUES ('Law Bit', 'Clothing', 13.88, 78);
INSERT INTO products (name, category, price, stock) VALUES ('Student Science', 'Electronics', 371.23, 83);
INSERT INTO products (name, category, price, stock) VALUES ('Building Tonight', 'Toys', 395.44, 78);
INSERT INTO products (name, category, price, stock) VALUES ('Real Rather', 'Electronics', 182.7, 26);
INSERT INTO products (name, category, price, stock) VALUES ('Understand Specific', 'Clothing', 302.38, 25);
INSERT INTO products (name, category, price, stock) VALUES ('Ok Set', 'Kitchen', 60.02, 81);
INSERT INTO products (name, category, price, stock) VALUES ('Tree Dinner', 'Electronics', 499.57, 58);
INSERT INTO products (name, category, price, stock) VALUES ('Law Live', 'Kitchen', 112.04, 8);
INSERT INTO products (name, category, price, stock) VALUES ('View Drive', 'Electronics', 399.14, 53);
INSERT INTO products (name, category, price, stock) VALUES ('Job Group', 'Clothing', 19.76, 90);

-- Orders
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (94, '2025-03-14', 387.95);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (31, '2024-05-05', 165.01);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (26, '2025-01-02', 159.93);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (41, '2024-03-03', 937.41);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (62, '2024-03-03', 330.37);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (22, '2024-01-21', 981.76);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (84, '2025-06-15', 279.8);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (11, '2024-12-02', 733.22);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (17, '2024-06-29', 209.11);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (9, '2023-09-23', 95.43);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (57, '2023-09-19', 455.39);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (45, '2024-05-29', 752.89);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (33, '2025-01-13', 933.68);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (18, '2024-04-16', 215.86);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (90, '2023-10-22', 849.16);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (30, '2023-08-31', 447.26);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (24, '2025-06-17', 503.6);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (84, '2024-09-01', 148.29);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (4, '2024-11-19', 736.25);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (27, '2024-05-14', 311.59);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (97, '2025-04-17', 255.88);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (77, '2025-06-05', 702.54);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (46, '2024-05-23', 962.82);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (9, '2025-05-18', 552.14);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (52, '2023-08-25', 593.79);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (68, '2024-02-14', 302.39);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (70, '2024-03-03', 611.47);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (28, '2023-10-02', 53.65);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (64, '2024-07-23', 380.86);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (23, '2023-11-09', 276.14);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (97, '2024-07-05', 584.12);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (87, '2025-03-29', 469.03);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (60, '2024-03-30', 287.79);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (43, '2024-08-28', 144.58);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (39, '2023-10-10', 916.0);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (48, '2024-02-07', 845.74);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (92, '2023-12-31', 405.01);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (23, '2024-05-27', 993.94);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (26, '2024-09-01', 780.75);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (3, '2025-01-29', 464.88);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (58, '2024-10-15', 383.61);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (38, '2024-11-23', 509.75);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (60, '2024-08-28', 53.92);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (16, '2024-10-06', 79.04);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (4, '2024-11-10', 740.54);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (51, '2024-12-06', 76.88);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (91, '2023-08-09', 61.93);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (98, '2024-02-03', 607.09);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (53, '2025-01-26', 840.74);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (65, '2025-05-22', 153.02);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (16, '2024-03-31', 943.38);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (23, '2023-11-28', 675.71);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (64, '2023-10-31', 398.94);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (43, '2024-11-10', 994.43);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (65, '2023-09-07', 221.51);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (1, '2025-01-10', 738.27);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (1, '2025-06-28', 296.12);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (3, '2023-09-24', 218.51);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (29, '2024-08-09', 386.39);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (1, '2024-04-18', 249.14);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (78, '2024-06-14', 503.26);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (84, '2023-11-11', 456.53);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (89, '2024-03-02', 170.89);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (40, '2024-03-12', 198.19);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (17, '2025-06-06', 718.51);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (21, '2024-09-26', 534.95);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (23, '2025-04-24', 477.75);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (36, '2023-11-09', 395.53);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (61, '2025-01-20', 114.62);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (29, '2023-08-24', 820.65);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (29, '2023-09-16', 703.59);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (58, '2024-06-06', 814.82);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (43, '2024-05-23', 500.96);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (94, '2024-10-04', 582.07);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (9, '2024-05-16', 437.69);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (17, '2023-12-23', 576.25);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (80, '2024-07-27', 979.92);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (70, '2024-03-27', 90.68);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (88, '2023-10-08', 557.33);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (25, '2024-11-25', 651.47);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (95, '2024-09-24', 870.93);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (65, '2024-08-07', 718.78);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (26, '2024-02-29', 753.73);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (59, '2023-12-27', 545.14);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (89, '2025-07-07', 401.65);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (66, '2023-08-28', 283.38);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (81, '2023-12-15', 261.3);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (32, '2025-06-09', 594.21);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (48, '2025-01-29', 716.89);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (57, '2025-01-27', 610.3);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (55, '2024-02-15', 866.34);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (79, '2023-10-14', 797.76);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (56, '2024-07-16', 440.9);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (19, '2024-05-28', 335.45);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (74, '2023-10-21', 670.41);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (33, '2024-08-11', 693.03);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (54, '2024-01-03', 369.78);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (6, '2024-08-30', 131.81);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (22, '2024-11-18', 311.27);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (31, '2024-04-02', 935.48);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (87, '2024-05-04', 403.31);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (24, '2025-01-11', 819.07);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (71, '2024-06-01', 559.44);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (35, '2024-06-19', 657.01);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (60, '2023-09-13', 460.46);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (31, '2024-03-03', 809.38);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (47, '2024-05-27', 904.68);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (100, '2024-05-09', 908.79);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (18, '2024-10-28', 680.5);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (65, '2024-02-15', 733.47);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (99, '2024-05-10', 215.44);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (25, '2025-06-24', 100.94);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (93, '2023-11-21', 990.5);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (27, '2025-06-10', 98.6);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (80, '2024-06-19', 948.1);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (41, '2024-12-04', 618.43);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (85, '2024-04-08', 665.39);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (23, '2024-06-02', 781.4);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (63, '2023-10-04', 185.04);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (66, '2024-06-01', 584.43);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (46, '2024-05-06', 684.98);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (62, '2023-09-14', 843.04);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (80, '2025-04-15', 221.23);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (40, '2025-01-14', 963.58);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (38, '2023-12-27', 428.53);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (25, '2025-02-07', 495.43);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (59, '2023-09-12', 195.84);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (4, '2024-10-23', 225.82);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (72, '2024-08-09', 273.71);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (10, '2023-12-07', 237.89);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (21, '2025-02-05', 957.76);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (39, '2024-03-31', 349.67);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (66, '2025-06-18', 736.67);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (35, '2024-11-01', 850.15);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (11, '2023-11-03', 300.69);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (81, '2023-10-02', 831.11);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (16, '2024-01-22', 644.28);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (73, '2023-11-22', 749.22);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (50, '2023-11-07', 241.66);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (27, '2025-01-23', 576.51);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (79, '2023-09-12', 479.18);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (75, '2025-06-13', 897.26);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (70, '2024-10-20', 592.04);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (71, '2024-06-22', 302.39);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (97, '2024-09-03', 571.91);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (86, '2024-09-14', 878.34);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (24, '2024-11-27', 451.53);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (49, '2025-04-23', 659.21);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (1, '2024-10-31', 743.73);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (83, '2025-07-09', 949.06);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (71, '2024-03-11', 277.45);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (30, '2025-06-27', 645.55);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (85, '2024-03-06', 617.06);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (52, '2024-06-04', 360.21);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (5, '2024-06-25', 657.11);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (75, '2024-10-22', 699.17);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (83, '2025-02-20', 322.48);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (45, '2024-09-23', 760.84);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (58, '2024-04-01', 568.48);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (19, '2023-09-11', 837.88);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (44, '2024-06-20', 831.7);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (55, '2023-08-15', 594.18);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (76, '2024-04-13', 87.31);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (37, '2024-02-13', 716.0);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (11, '2024-11-01', 241.66);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (39, '2025-07-02', 691.14);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (31, '2023-09-23', 248.17);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (73, '2024-09-25', 664.72);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (86, '2024-04-25', 323.21);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (78, '2024-09-15', 391.49);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (59, '2025-06-15', 574.37);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (10, '2025-01-09', 786.53);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (21, '2023-08-17', 603.77);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (39, '2025-05-13', 969.99);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (73, '2024-09-08', 187.69);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (20, '2023-12-03', 725.6);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (93, '2024-10-03', 286.43);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (45, '2024-07-19', 980.95);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (64, '2025-06-18', 62.01);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (40, '2024-06-12', 361.91);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (11, '2025-03-02', 922.07);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (44, '2025-03-22', 721.61);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (47, '2025-07-06', 292.66);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (30, '2023-09-18', 816.1);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (40, '2024-11-02', 350.43);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (39, '2023-08-16', 693.64);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (42, '2024-12-17', 895.64);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (44, '2025-07-12', 682.21);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (70, '2024-08-05', 109.09);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (54, '2024-10-06', 855.22);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (88, '2024-04-10', 736.77);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (4, '2025-05-20', 435.81);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (74, '2024-04-27', 881.08);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (99, '2025-02-04', 339.28);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (20, '2024-11-26', 554.97);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (45, '2023-08-26', 932.23);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (62, '2024-10-22', 805.98);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (2, '2024-03-19', 766.24);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (28, '2024-03-16', 769.77);
INSERT INTO orders (customer_id, order_date, total_amount) VALUES (31, '2024-08-29', 866.67);

-- Order Items
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (1, 7, 1, 95.78);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (2, 38, 4, 127.78);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (3, 28, 1, 228.88);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (3, 46, 1, 110.98);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (3, 15, 2, 197.71);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (4, 45, 4, 103.88);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (5, 20, 3, 84.74);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (6, 23, 3, 97.36);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (6, 18, 2, 215.66);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (7, 9, 1, 111.17);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (8, 8, 3, 192.73);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (8, 29, 5, 281.94);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (8, 40, 1, 203.8);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (9, 2, 3, 268.51);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (9, 28, 5, 162.46);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (10, 11, 2, 83.2);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (11, 19, 3, 94.98);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (11, 9, 5, 123.59);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (12, 8, 3, 47.62);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (12, 34, 3, 147.06);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (13, 45, 3, 156.57);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (13, 48, 3, 63.94);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (13, 26, 3, 77.26);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (14, 3, 3, 194.57);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (15, 16, 2, 32.85);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (16, 48, 4, 140.76);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (16, 26, 4, 113.43);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (16, 23, 1, 166.74);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (17, 23, 4, 250.66);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (18, 40, 2, 253.85);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (19, 41, 2, 252.02);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (19, 33, 3, 94.3);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (19, 3, 2, 298.55);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (20, 48, 2, 108.79);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (21, 28, 2, 174.69);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (21, 17, 3, 235.72);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (22, 24, 2, 263.19);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (22, 7, 2, 131.62);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (22, 4, 5, 75.5);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (23, 40, 5, 227.87);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (24, 25, 5, 120.67);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (24, 3, 1, 283.95);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (25, 12, 4, 160.66);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (25, 20, 2, 147.79);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (25, 8, 3, 37.93);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (26, 36, 2, 94.53);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (26, 49, 4, 55.97);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (27, 6, 1, 33.21);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (27, 1, 5, 293.8);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (28, 1, 1, 192.06);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (28, 44, 3, 18.51);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (28, 15, 2, 94.59);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (29, 32, 3, 202.61);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (29, 8, 4, 125.81);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (30, 26, 5, 123.38);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (31, 26, 2, 97.27);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (31, 42, 5, 13.68);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (32, 50, 2, 218.42);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (32, 19, 2, 92.35);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (32, 38, 4, 278.01);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (33, 14, 2, 47.35);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (33, 5, 1, 38.51);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (33, 36, 3, 282.89);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (34, 20, 4, 208.22);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (34, 6, 5, 289.42);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (34, 5, 3, 36.2);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (35, 32, 4, 171.02);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (35, 28, 3, 39.47);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (35, 37, 4, 21.13);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (36, 34, 1, 146.64);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (36, 15, 5, 287.43);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (36, 49, 3, 243.75);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (37, 7, 4, 27.67);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (37, 48, 5, 70.9);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (37, 16, 1, 239.5);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (38, 48, 2, 278.31);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (38, 29, 4, 205.04);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (39, 33, 3, 42.4);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (40, 32, 4, 162.9);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (40, 2, 5, 130.9);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (40, 15, 5, 35.59);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (41, 3, 1, 184.21);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (41, 47, 3, 103.1);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (42, 12, 1, 91.15);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (42, 35, 1, 242.06);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (42, 13, 5, 69.25);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (43, 20, 4, 179.88);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (44, 15, 1, 89.53);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (45, 27, 5, 280.91);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (46, 49, 4, 205.89);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (47, 26, 2, 264.9);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (47, 29, 3, 190.45);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (47, 7, 1, 240.19);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (48, 12, 5, 85.36);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (48, 25, 3, 110.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (48, 30, 3, 129.84);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (49, 17, 3, 157.69);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (49, 37, 3, 147.49);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (49, 30, 5, 10.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (50, 43, 5, 242.55);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (51, 34, 5, 63.48);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (52, 47, 3, 244.01);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (52, 39, 3, 212.02);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (53, 6, 1, 100.03);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (53, 19, 1, 115.54);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (53, 32, 1, 157.31);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (54, 18, 3, 210.33);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (54, 35, 3, 176.69);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (54, 48, 5, 277.62);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (55, 44, 4, 176.82);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (55, 32, 4, 112.39);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (56, 50, 2, 136.23);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (57, 32, 1, 139.89);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (57, 28, 2, 237.17);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (57, 13, 1, 269.81);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (58, 9, 1, 108.33);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (58, 42, 4, 102.48);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (58, 46, 3, 275.08);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (59, 30, 4, 10.81);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (59, 24, 3, 16.23);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (59, 32, 1, 47.61);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (60, 47, 5, 124.77);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (61, 46, 3, 48.88);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (61, 10, 5, 273.77);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (61, 47, 2, 143.13);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (62, 36, 1, 276.46);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (63, 6, 5, 112.8);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (63, 25, 2, 166.97);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (64, 2, 4, 210.37);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (64, 12, 2, 266.5);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (64, 5, 3, 188.64);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (65, 12, 3, 135.55);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (66, 45, 1, 134.49);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (66, 8, 5, 27.75);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (66, 37, 4, 194.66);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (67, 50, 2, 208.5);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (68, 21, 4, 62.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (68, 41, 5, 189.62);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (68, 18, 4, 60.24);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (69, 22, 3, 96.32);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (69, 20, 2, 162.58);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (70, 44, 4, 248.18);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (70, 39, 1, 294.76);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (70, 34, 2, 189.39);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (71, 25, 5, 241.38);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (71, 13, 5, 75.33);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (71, 33, 3, 281.15);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (72, 18, 5, 141.04);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (72, 10, 2, 269.1);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (72, 24, 3, 200.14);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (73, 20, 4, 91.17);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (73, 12, 2, 43.17);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (74, 18, 1, 157.01);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (74, 29, 2, 102.51);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (75, 43, 3, 41.22);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (75, 13, 3, 276.09);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (75, 39, 2, 41.43);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (76, 34, 2, 24.11);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (77, 13, 1, 185.44);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (78, 7, 3, 178.57);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (78, 43, 2, 154.57);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (79, 14, 3, 185.83);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (80, 9, 1, 212.65);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (80, 30, 4, 277.15);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (81, 26, 1, 41.38);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (82, 44, 5, 193.42);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (83, 10, 4, 95.27);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (84, 13, 4, 51.77);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (84, 40, 1, 205.56);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (85, 12, 2, 141.94);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (85, 23, 4, 135.61);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (85, 25, 1, 118.63);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (86, 23, 4, 149.7);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (86, 12, 2, 68.08);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (87, 11, 5, 220.49);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (87, 6, 2, 188.41);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (87, 14, 2, 131.29);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (88, 50, 1, 265.5);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (88, 14, 1, 262.12);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (88, 4, 3, 291.89);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (89, 27, 4, 126.59);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (90, 39, 2, 136.28);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (90, 30, 1, 223.21);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (91, 46, 5, 104.43);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (91, 37, 4, 86.58);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (92, 21, 3, 189.82);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (92, 41, 5, 242.65);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (92, 48, 3, 264.04);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (93, 26, 4, 270.39);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (93, 4, 5, 95.21);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (94, 10, 3, 166.91);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (94, 12, 3, 92.17);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (95, 22, 1, 230.7);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (95, 44, 5, 167.11);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (96, 23, 1, 67.58);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (96, 30, 5, 242.48);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (97, 41, 3, 152.52);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (98, 47, 2, 213.49);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (99, 37, 3, 127.06);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (99, 25, 4, 212.87);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (100, 45, 4, 46.39);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (100, 24, 5, 217.35);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (100, 18, 3, 13.97);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (101, 7, 5, 244.54);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (102, 28, 1, 278.96);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (102, 26, 3, 74.36);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (102, 23, 2, 228.75);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (103, 36, 5, 103.69);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (103, 5, 2, 212.54);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (104, 23, 5, 261.41);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (104, 27, 3, 278.42);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (104, 1, 5, 163.26);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (105, 17, 2, 118.63);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (105, 9, 5, 19.28);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (105, 28, 4, 27.52);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (106, 5, 2, 219.45);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (106, 10, 4, 31.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (107, 3, 3, 101.02);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (108, 24, 2, 134.2);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (109, 49, 1, 128.9);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (109, 47, 1, 263.9);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (110, 18, 2, 115.36);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (111, 20, 1, 280.29);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (111, 27, 5, 279.77);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (111, 3, 5, 192.52);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (112, 24, 5, 40.07);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (113, 49, 1, 194.41);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (113, 44, 4, 190.14);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (113, 11, 3, 71.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (114, 30, 4, 233.98);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (114, 38, 2, 172.47);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (115, 22, 5, 60.98);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (116, 16, 1, 149.13);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (116, 46, 1, 122.22);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (117, 48, 3, 23.75);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (118, 2, 3, 204.98);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (119, 44, 4, 43.68);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (119, 39, 5, 233.45);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (120, 50, 5, 78.7);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (120, 8, 4, 42.55);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (120, 6, 3, 86.25);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (121, 33, 4, 185.1);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (122, 32, 5, 59.89);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (122, 18, 2, 125.08);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (123, 10, 1, 46.75);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (123, 20, 4, 168.78);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (123, 6, 1, 25.75);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (124, 15, 2, 64.47);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (124, 46, 2, 62.36);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (125, 14, 4, 47.01);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (125, 13, 5, 166.78);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (126, 17, 4, 289.74);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (127, 29, 5, 217.85);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (128, 44, 3, 221.2);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (128, 16, 2, 200.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (128, 43, 4, 276.27);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (129, 19, 2, 162.91);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (130, 9, 3, 109.57);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (131, 39, 2, 291.95);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (131, 21, 4, 55.93);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (131, 20, 1, 104.25);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (132, 4, 3, 103.21);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (133, 10, 4, 40.56);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (133, 42, 3, 266.03);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (133, 34, 1, 273.73);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (134, 46, 3, 72.3);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (135, 16, 5, 127.59);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (135, 3, 5, 233.35);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (136, 38, 3, 263.8);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (137, 37, 2, 169.83);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (138, 27, 3, 220.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (139, 3, 3, 126.41);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (139, 28, 1, 213.89);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (140, 39, 1, 285.67);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (141, 29, 4, 286.21);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (141, 32, 5, 11.92);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (142, 8, 5, 285.96);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (142, 24, 2, 73.35);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (142, 42, 2, 57.14);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (143, 34, 3, 41.11);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (143, 22, 3, 101.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (143, 42, 4, 115.77);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (144, 13, 5, 217.81);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (144, 16, 3, 192.08);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (145, 49, 4, 253.67);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (145, 37, 2, 31.83);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (146, 21, 2, 273.15);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (146, 10, 4, 83.04);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (146, 1, 1, 186.59);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (147, 15, 1, 139.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (147, 14, 2, 106.56);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (148, 7, 5, 78.3);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (149, 5, 4, 70.85);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (149, 32, 4, 51.09);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (149, 36, 3, 264.35);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (150, 28, 4, 103.9);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (151, 36, 5, 244.63);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (151, 26, 2, 196.1);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (152, 28, 5, 291.58);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (152, 44, 5, 150.14);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (153, 32, 3, 261.39);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (153, 48, 3, 155.05);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (154, 37, 4, 43.39);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (155, 26, 1, 268.61);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (156, 21, 3, 255.04);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (156, 48, 5, 157.77);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (156, 3, 1, 143.13);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (157, 4, 3, 77.15);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (157, 32, 5, 280.79);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (157, 40, 2, 58.92);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (158, 30, 4, 252.4);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (158, 24, 4, 279.44);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (158, 31, 2, 99.57);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (159, 27, 4, 213.49);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (159, 35, 5, 224.41);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (160, 31, 3, 227.29);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (160, 33, 2, 20.57);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (160, 47, 2, 109.68);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (161, 36, 3, 275.78);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (161, 50, 3, 11.42);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (161, 30, 4, 220.15);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (162, 1, 3, 94.18);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (163, 28, 4, 297.66);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (164, 50, 2, 43.19);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (165, 39, 4, 124.59);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (165, 14, 3, 200.81);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (165, 38, 1, 108.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (166, 28, 5, 70.37);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (166, 13, 2, 137.63);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (166, 45, 1, 14.06);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (167, 16, 4, 101.9);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (168, 35, 2, 42.42);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (168, 2, 4, 222.07);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (168, 39, 4, 144.58);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (169, 11, 2, 155.69);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (170, 4, 1, 42.52);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (170, 28, 2, 291.11);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (171, 43, 5, 215.87);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (172, 41, 2, 51.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (173, 1, 4, 208.95);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (174, 28, 3, 283.65);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (174, 48, 2, 14.26);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (174, 7, 2, 113.51);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (175, 35, 3, 228.22);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (176, 28, 1, 137.53);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (176, 18, 5, 14.64);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (176, 40, 4, 261.74);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (177, 24, 5, 245.35);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (177, 19, 2, 237.82);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (177, 41, 1, 128.91);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (178, 27, 2, 219.12);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (179, 8, 3, 153.88);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (179, 22, 3, 40.41);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (179, 37, 5, 160.04);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (180, 44, 2, 82.61);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (180, 19, 2, 256.99);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (181, 47, 4, 104.43);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (181, 39, 1, 121.14);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (181, 3, 4, 279.71);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (182, 30, 1, 238.77);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (182, 3, 1, 185.94);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (183, 25, 4, 54.36);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (183, 35, 5, 99.36);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (184, 31, 1, 199.86);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (184, 38, 2, 241.46);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (184, 21, 5, 109.89);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (185, 33, 3, 83.4);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (185, 13, 1, 220.08);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (185, 2, 4, 231.29);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (186, 41, 5, 186.35);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (187, 32, 3, 275.71);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (187, 46, 3, 133.79);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (188, 10, 2, 69.44);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (189, 10, 3, 99.59);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (189, 30, 4, 127.56);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (190, 1, 5, 130.53);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (191, 16, 3, 94.84);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (191, 45, 2, 48.18);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (191, 2, 3, 225.7);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (192, 18, 1, 67.11);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (192, 8, 1, 187.17);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (193, 32, 3, 258.54);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (193, 45, 1, 131.8);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (193, 8, 1, 192.89);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (194, 49, 3, 65.6);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (195, 21, 4, 293.52);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (195, 45, 2, 79.42);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (195, 40, 3, 189.25);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (196, 17, 5, 44.49);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (196, 8, 1, 70.74);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (197, 42, 1, 89.01);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (198, 1, 1, 129.74);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (199, 45, 5, 13.25);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (199, 26, 1, 238.05);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (200, 24, 5, 170.88);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (200, 29, 5, 105.53);
INSERT INTO order_items (order_id, product_id, quantity, unit_price) VALUES (200, 8, 3, 112.25);

-- Reviews
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (25, 90, 3, 'Exist rich prevent trade their four.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (10, 50, 2, 'Professional true financial prevent product can remember be.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (25, 7, 2, 'Heavy social spend prove stock school rate.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (19, 81, 1, 'Behavior provide meet adult final week game.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (37, 73, 4, 'Court yourself choice fast small medical music.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (34, 81, 4, 'Also from short capital heavy class story.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (23, 97, 1, 'Speak close join improve put down know expect.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (25, 60, 2, 'Doctor dream whole six tough create question.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (4, 31, 5, 'Worker left example high month whom stage.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (16, 79, 4, 'Catch economic political them never bill suffer surface.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (33, 51, 5, 'Base civil last message store.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (44, 39, 4, 'Watch develop later glass.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (40, 34, 5, 'Increase how hear.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (30, 82, 2, 'Yes heart agreement us stuff practice.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (16, 76, 5, 'Case expert stop receive.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (41, 66, 4, 'Serve light past town.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (49, 64, 1, 'Eight strong nature.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (50, 40, 3, 'Month book explain feeling answer information soldier lead.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (16, 6, 1, 'Student matter movie place.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (39, 83, 1, 'Drop century investment pass drive indicate professor.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (14, 93, 3, 'Model guess well name.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (34, 94, 3, 'Never hospital like player wonder effect administration.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (16, 18, 2, 'General run pick sign.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (16, 35, 1, 'Card good full poor store range.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (6, 41, 1, 'Place specific as simply leader fall analysis.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (18, 62, 2, 'Though firm financial huge spring.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (34, 82, 3, 'Education send course ground sit tend forward.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (6, 13, 2, 'Son join hundred keep.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (48, 34, 4, 'Fund cost reality happen something entire.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (10, 85, 4, 'Risk bad own state.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (27, 100, 2, 'Family bill foreign fast knowledge response coach.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (31, 66, 5, 'Goal amount thank good your ever.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (1, 93, 3, 'Avoid point guy song.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (22, 35, 2, 'Well central parent sit.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (30, 95, 5, 'Call door population.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (10, 59, 3, 'Him note painting quickly we head.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (15, 95, 3, 'Off morning huge power.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (15, 56, 5, 'Whether ago control military trial.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (24, 20, 4, 'Energy employee land you.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (46, 71, 4, 'Really your customer career available.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (28, 63, 5, 'Together knowledge because radio.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (17, 43, 2, 'Property remember nearly face feel church.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (42, 71, 3, 'Soldier meeting building cut.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (42, 100, 2, 'Door management guess occur.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (41, 78, 5, 'Sound necessary partner beat finally yourself rest.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (30, 51, 5, 'Improve important offer by first avoid letter.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (48, 55, 2, 'General there sister policy consider whom item.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (31, 12, 1, 'Story million fight class.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (12, 97, 4, 'Generation wait thus suffer economy.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (32, 30, 4, 'Ever person pass behavior political option oil.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (49, 18, 5, 'Probably result painting successful.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (24, 74, 5, 'American tell ball we side enough decision.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (16, 27, 4, 'Indicate police marriage phone face what lot.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (14, 63, 1, 'Father authority art keep machine daughter.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (36, 9, 3, 'Century technology floor write generation human set middle.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (16, 98, 5, 'Five letter environment easy.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (46, 92, 4, 'Anything war ten industry.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (22, 97, 1, 'Spend value return couple.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (31, 48, 2, 'Marriage method material final.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (6, 97, 5, 'Bed hotel lead.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (41, 12, 5, 'Democrat good anything manager think.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (21, 18, 3, 'Experience account blue care enough hand idea.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (12, 8, 1, 'Hundred now crime.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (38, 25, 1, 'Eye hit late near stay perhaps particularly.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (44, 99, 2, 'Window hour some fund.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (39, 37, 3, 'Sense current meeting matter and case.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (3, 21, 3, 'Sound mind chance throw cause use.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (11, 6, 2, 'Class wrong school federal from stock.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (37, 37, 4, 'Majority none little admit former body indicate.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (26, 65, 3, 'Someone rise read ago listen.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (16, 50, 3, 'Officer return on color pick people subject challenge.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (25, 50, 3, 'All way body affect finish.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (48, 16, 2, 'Include data maybe particularly.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (19, 91, 2, 'Their save artist catch debate foot production.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (26, 42, 3, 'Heavy what least mouth national put test.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (40, 82, 1, 'Particular court east newspaper different.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (50, 42, 4, 'Side relate real major look.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (3, 100, 5, 'Value somebody event business quality here woman.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (28, 99, 3, 'West source fact explain research get.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (2, 73, 4, 'Pretty section degree still even no.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (42, 23, 1, 'Case past only drug prove.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (44, 36, 4, 'Difficult do beyond form line race case.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (13, 96, 1, 'Within citizen present thing little practice sense.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (44, 61, 3, 'Fly position traditional become off.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (40, 90, 4, 'School sure also TV individual study value.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (4, 20, 2, 'Young however many.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (38, 18, 3, 'Theory across nothing blue work.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (19, 93, 4, 'Lawyer political modern threat care.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (26, 68, 5, 'Life cover both class learn either control.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (3, 88, 2, 'So nothing serious compare task today.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (50, 88, 4, 'Middle beautiful protect continue cell food.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (27, 41, 2, 'According himself land environment form.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (50, 32, 2, 'Reveal activity president realize artist brother fill if.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (36, 89, 4, 'Type thousand show real police wait happen.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (29, 40, 4, 'Despite card check security paper.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (4, 63, 3, 'Reduce tree serious soon stay seven.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (48, 96, 5, 'Their bank land region back nor article natural.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (48, 31, 3, 'Dark Mr clearly take kind quite response.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (15, 78, 4, 'Before member speak law message lead around.');
INSERT INTO reviews (product_id, customer_id, rating, comment) VALUES (11, 30, 5, 'Pull final against effort able design authority.');
